# Name
spring.application.name=TrungTamTiengAnh

# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://localhost:3306/trungtamtienganh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080

# ===== GOOGLE GEMINI API =====
gemini.api.key=AIzaSyAe2P32qK7ZVqvPS9mbB4GN0MQ2MZMtlYc
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=

# ===== MAIL CONFIGURATION =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nghoangsang@gmail.com
spring.mail.password=your_app_password_here
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
admin.password=123
